# Generated by Django 5.0.6 on 2024-05-28 17:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='preapproved_at',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2024, 5, 28, 17, 52, 26, 225385, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='score',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
