# Generated by Django 5.0.6 on 2024-05-31 08:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='preapproved_at',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2024, 5, 31, 8, 30, 20, 86184, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
    ]
