# Generated by Django 5.0.6 on 2024-05-28 18:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_preapproved_at_alter_customer_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='preapproved_at',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2024, 5, 28, 18, 4, 51, 725298, tzinfo=datetime.timezone.utc))]),
        ),
    ]
